version: 1.0.{build}
image: Visual Studio 2017
build:
  project: ThreatCheck\ThreatCheck.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: ThreatCheck\Release\x64\*.exe
only_commits:
  files:
    - ThreatCheck/
