version: 1.0.{build}
image: Visual Studio 2017
before_build:
  - nuget restore ThreatCheck/
build:
  project: ThreatCheck\ThreatCheck.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: ThreatCheck\ThreatCheck\bin\Debug\*.exe
only_commits:
  files:
    - ThreatCheck/
